### ISSUE TITLE
Error due to line 226 in market.py

### ISSUE THREAD

**Issue by ShilazTech** [holgern/steemengine#2]
I got cancellation working by doing below change to market.py line 226
contract_payload = {"type": order_type, "id": int(order_id)}   to    contract_payload = {"type": order_type, "id": order_id}

now I can give trxID as order_id and it works.

I do not know how to submit the pull request and submitted it here as issue.

Pls update the API as freshly downloaded API gives same old error "invalid parameters"

**Comment by holgern** [comment]
Fixed in https://github.com/holgern/steemengine/commit/8f806a1b0bef6bfdc72620dcc1fee47a643196cf
